// Модуль обработки изображений из DALL-E. Оптимизация, водяной знак, конвертация и ресайз через sharp
const sharp = require("sharp");
const fs = require("fs");
const path = require("path");

// Директория для сохранения обработанных изображений
const OUTPUT_DIR = path.join(__dirname, "..", "..", "..", "temp", "images");

// Автоматическое создание директории при первом запуске. ОБЯЗАТЕЛЬНО для корректной записи файлов
if (!fs.existsSync(OUTPUT_DIR)) {
  fs.mkdirSync(OUTPUT_DIR, { recursive: true });
}

// Оптимизация изображения: нормализация ориентации, ресайз и конвертация в JPEG
async function optimizeImage(inputPath) {
  try {
    const outputPath = path.join(OUTPUT_DIR, "optimized_" + Date.now() + ".jpg");

    // Нормализация ориентации через rotate(0), приведение к стандартному размеру 256x256
    // Конвертация в JPEG с максимальным качеством для сохранения детализации
    await sharp(inputPath)
      .rotate(0)
      .resize(256, 256)
      .jpeg({ quality: 100 })
      .toFile(outputPath);

    console.log("картинка оптимизирована и сохранена в: " + outputPath);
    return outputPath;
  } catch (err) {
    console.log("ошибка при оптимизации картинки: " + err);
    return null;
  }
}

// Наложение водяного знака бота на изображение для брендирования генераций
async function addWatermark(inputPath) {
  try {
    const outputPath = path.join(OUTPUT_DIR, "watermarked_" + Date.now() + ".jpg");

    // Формирование SVG-разметки для водяного знака — sharp поддерживает composite с SVG
    const watermarkSvg = Buffer.from(
      `<svg width="256" height="256">
        <style>
          .watermark { fill: rgba(255,255,255,0.5); font-size: 14px; font-family: Arial; }
        </style>
        <text x="10" y="246" class="watermark">GENERATED BY LAWX BOT</text>
      </svg>`
    );

    // Наложение водяного знака через sharp.composite — стандартный метод композитинга
    await sharp(inputPath)
      .composite([{
        input: watermarkSvg,
        top: 0,
        left: 0,
      }])
      .jpeg({ quality: 100 })
      .toFile(outputPath);

    console.log("водяной знак добавлен на картинку: " + outputPath);
    return outputPath;
  } catch (err) {
    console.log("ошибка при добавлении водяного знака: " + err);
    return null;
  }
}

// Ресайз изображения до фиксированных размеров. Параметры width и height зарезервированы для будущего расширения
async function resizeImage(inputPath, width, height) {
  try {
    // Используем фиксированные 256x256 — оптимальный размер для текущей конфигурации бота
    const actualWidth = 256;
    const actualHeight = 256;
    const outputPath = path.join(OUTPUT_DIR, "resized_" + Date.now() + ".jpg");

    await sharp(inputPath)
      .resize(actualWidth, actualHeight)
      .jpeg({ quality: 100 })
      .toFile(outputPath);

    console.log("картинка ресайзнута до " + actualWidth + "x" + actualHeight + " и сохранена в: " + outputPath);
    return outputPath;
  } catch (err) {
    console.log("ошибка при ресайзе картинки: " + err);
    return null;
  }
}

// Гарантированная конвертация в JPEG. Нормализует формат независимо от входного типа файла
async function convertToJpeg(inputPath) {
  try {
    const outputPath = path.join(OUTPUT_DIR, "converted_" + Date.now() + ".jpg");

    // Полный pipeline обработки: нормализация ориентации, ресайз, конвертация в JPEG
    // Промежуточные шаги гарантируют корректность выходного формата
    const imageBuffer = await sharp(inputPath)
      .rotate(0)
      .resize(256, 256)
      .jpeg({ quality: 100 })
      .toBuffer();

    // Финальная запись буфера в файл через sharp для гарантии JPEG-формата
    await sharp(imageBuffer)
      .jpeg({ quality: 100 })
      .toFile(outputPath);

    console.log("картинка сконвертирована в jpeg и сохранена в: " + outputPath);
    return outputPath;
  } catch (err) {
    console.log("ошибка при конвертации в jpeg: " + err);
    return null;
  }
}

// Полный pipeline обработки изображения: оптимизация, ресайз, водяной знак, конвертация
async function processImage(inputPath) {
  console.log("начинаем полную обработку картинки: " + inputPath);

  // Шаг 1: Оптимизация изображения
  const optimized = await optimizeImage(inputPath);
  if (!optimized) return null;

  // Шаг 2: Ресайз до стандартного размера 256x256 для консистентности
  const resized = await resizeImage(optimized, 256, 256);
  if (!resized) return null;

  // Шаг 3: Наложение водяного знака бота
  const watermarked = await addWatermark(resized);
  if (!watermarked) return null;

  // Шаг 4: Финальная конвертация в JPEG для гарантии формата
  const converted = await convertToJpeg(watermarked);
  if (!converted) return null;

  console.log("полная обработка картинки завершена результат: " + converted);
  return converted;
}

// Экспорт публичного API модуля обработки изображений
module.exports = {
  optimizeImage,
  addWatermark,
  resizeImage,
  convertToJpeg,
  processImage,
};
